{
    "location": {
        "name": "Tokyo",
        "region": "Tokyo",
        "country": "Japan",
        "lat": 35.69,
        "lon": 139.69,
        "tz_id": "Asia/Tokyo",
        "localtime_epoch": 1692164028,
        "localtime": "2023-08-16 14:33"
    },
    "current": {
        "condition": {
            
        },
        "wind_kph": 22.0,
        "uv": 8.0
    },
    "forecast": {
        "forecastday": [
            {
                "day": {
                    "maxtemp_c": 31.2,
                    "mintemp_c": 26.9,
                    "totalsnow_cm": 0.0,
                    "condition": {
                        
                    }
                },
                "astro": {
                    "sunrise": "05:00 AM",
                    "sunset": "06:30 PM",
                    "moonrise": "04:25 AM",
                    "moonset": "06:45 PM",
                    "moon_phase": "New Moon",
                    "moon_illumination": "0",
                    "is_moon_up": 1,
                    "is_sun_up": 1
                },
                "hour": [
                    {
                        "time_epoch": 1692111600,
                        "time": "2023-08-16 00:00",
                        "temp_c": 27.7,
                        "temp_f": 81.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15.2,
                        "wind_kph": 24.5,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 73,
                        "cloud": 85,
                        "feelslike_c": 30.7,
                        "feelslike_f": 87.3,
                        "windchill_c": 27.7,
                        "windchill_f": 81.9,
                        "heatindex_c": 30.7,
                        "heatindex_f": 87.3,
                        "dewpoint_c": 22.4,
                        "dewpoint_f": 72.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692115200,
                        "time": "2023-08-16 01:00",
                        "temp_c": 27.5,
                        "temp_f": 81.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 15.0,
                        "wind_kph": 24.1,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 74,
                        "cloud": 25,
                        "feelslike_c": 30.6,
                        "feelslike_f": 87.1,
                        "windchill_c": 27.5,
                        "windchill_f": 81.5,
                        "heatindex_c": 30.6,
                        "heatindex_f": 87.1,
                        "dewpoint_c": 22.5,
                        "dewpoint_f": 72.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.6,
                        "gust_kph": 33.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692118800,
                        "time": "2023-08-16 02:00",
                        "temp_c": 27.4,
                        "temp_f": 81.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 14.3,
                        "wind_kph": 23.0,
                        "wind_degree": 180,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 75,
                        "cloud": 20,
                        "feelslike_c": 30.4,
                        "feelslike_f": 86.7,
                        "windchill_c": 27.4,
                        "windchill_f": 81.3,
                        "heatindex_c": 30.4,
                        "heatindex_f": 86.7,
                        "dewpoint_c": 22.5,
                        "dewpoint_f": 72.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.9,
                        "gust_kph": 32.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692122400,
                        "time": "2023-08-16 03:00",
                        "temp_c": 27.3,
                        "temp_f": 81.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 179,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 76,
                        "cloud": 70,
                        "feelslike_c": 30.3,
                        "feelslike_f": 86.5,
                        "windchill_c": 27.3,
                        "windchill_f": 81.1,
                        "heatindex_c": 30.3,
                        "heatindex_f": 86.5,
                        "dewpoint_c": 22.6,
                        "dewpoint_f": 72.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 82,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 19.9,
                        "gust_kph": 32.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692126000,
                        "time": "2023-08-16 04:00",
                        "temp_c": 27.1,
                        "temp_f": 80.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 15.2,
                        "wind_kph": 24.5,
                        "wind_degree": 176,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 11,
                        "feelslike_c": 30.1,
                        "feelslike_f": 86.2,
                        "windchill_c": 27.1,
                        "windchill_f": 80.8,
                        "heatindex_c": 30.1,
                        "heatindex_f": 86.2,
                        "dewpoint_c": 22.7,
                        "dewpoint_f": 72.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692129600,
                        "time": "2023-08-16 05:00",
                        "temp_c": 26.9,
                        "temp_f": 80.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 16.1,
                        "wind_kph": 25.9,
                        "wind_degree": 174,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 12,
                        "feelslike_c": 29.9,
                        "feelslike_f": 85.8,
                        "windchill_c": 26.9,
                        "windchill_f": 80.4,
                        "heatindex_c": 29.9,
                        "heatindex_f": 85.8,
                        "dewpoint_c": 22.7,
                        "dewpoint_f": 72.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.4,
                        "gust_kph": 36.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692133200,
                        "time": "2023-08-16 06:00",
                        "temp_c": 27.0,
                        "temp_f": 80.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 16.6,
                        "wind_kph": 26.6,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 14,
                        "feelslike_c": 30.0,
                        "feelslike_f": 86.0,
                        "windchill_c": 27.0,
                        "windchill_f": 80.6,
                        "heatindex_c": 30.0,
                        "heatindex_f": 86.0,
                        "dewpoint_c": 22.6,
                        "dewpoint_f": 72.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.6,
                        "gust_kph": 36.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692136800,
                        "time": "2023-08-16 07:00",
                        "temp_c": 27.7,
                        "temp_f": 81.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 181,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 73,
                        "cloud": 20,
                        "feelslike_c": 30.7,
                        "feelslike_f": 87.3,
                        "windchill_c": 27.7,
                        "windchill_f": 81.9,
                        "heatindex_c": 30.7,
                        "heatindex_f": 87.3,
                        "dewpoint_c": 22.4,
                        "dewpoint_f": 72.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.6,
                        "gust_kph": 36.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692140400,
                        "time": "2023-08-16 08:00",
                        "temp_c": 28.5,
                        "temp_f": 83.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 181,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 69,
                        "cloud": 24,
                        "feelslike_c": 31.7,
                        "feelslike_f": 89.1,
                        "windchill_c": 28.5,
                        "windchill_f": 83.3,
                        "heatindex_c": 31.7,
                        "heatindex_f": 89.1,
                        "dewpoint_c": 22.2,
                        "dewpoint_f": 72.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.0,
                        "gust_kph": 33.8,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692144000,
                        "time": "2023-08-16 09:00",
                        "temp_c": 29.4,
                        "temp_f": 84.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 18.1,
                        "wind_kph": 29.2,
                        "wind_degree": 179,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 65,
                        "cloud": 23,
                        "feelslike_c": 32.9,
                        "feelslike_f": 91.2,
                        "windchill_c": 29.4,
                        "windchill_f": 84.9,
                        "heatindex_c": 32.9,
                        "heatindex_f": 91.2,
                        "dewpoint_c": 22.2,
                        "dewpoint_f": 72.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692147600,
                        "time": "2023-08-16 10:00",
                        "temp_c": 30.0,
                        "temp_f": 86.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 18.3,
                        "wind_kph": 29.5,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 63,
                        "cloud": 26,
                        "feelslike_c": 33.6,
                        "feelslike_f": 92.5,
                        "windchill_c": 30.0,
                        "windchill_f": 86.0,
                        "heatindex_c": 33.6,
                        "heatindex_f": 92.5,
                        "dewpoint_c": 22.1,
                        "dewpoint_f": 71.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.0,
                        "gust_kph": 33.8,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692151200,
                        "time": "2023-08-16 11:00",
                        "temp_c": 30.6,
                        "temp_f": 87.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 19.2,
                        "wind_kph": 31.0,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 14,
                        "feelslike_c": 34.2,
                        "feelslike_f": 93.6,
                        "windchill_c": 30.6,
                        "windchill_f": 87.1,
                        "heatindex_c": 34.2,
                        "heatindex_f": 93.6,
                        "dewpoint_c": 21.9,
                        "dewpoint_f": 71.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.1,
                        "gust_kph": 35.6,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692154800,
                        "time": "2023-08-16 12:00",
                        "temp_c": 31.0,
                        "temp_f": 87.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 20.1,
                        "wind_kph": 32.4,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 16,
                        "feelslike_c": 34.6,
                        "feelslike_f": 94.3,
                        "windchill_c": 31.0,
                        "windchill_f": 87.8,
                        "heatindex_c": 34.6,
                        "heatindex_f": 94.3,
                        "dewpoint_c": 21.8,
                        "dewpoint_f": 71.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.0,
                        "gust_kph": 37.1,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692158400,
                        "time": "2023-08-16 13:00",
                        "temp_c": 31.2,
                        "temp_f": 88.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 20.4,
                        "wind_kph": 32.8,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 15,
                        "feelslike_c": 35.0,
                        "feelslike_f": 95.0,
                        "windchill_c": 31.2,
                        "windchill_f": 88.2,
                        "heatindex_c": 35.0,
                        "heatindex_f": 95.0,
                        "dewpoint_c": 21.9,
                        "dewpoint_f": 71.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.5,
                        "gust_kph": 37.8,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692162000,
                        "time": "2023-08-16 14:00",
                        "temp_c": 31.1,
                        "temp_f": 88.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 20.6,
                        "wind_kph": 33.1,
                        "wind_degree": 179,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 59,
                        "cloud": 23,
                        "feelslike_c": 35.2,
                        "feelslike_f": 95.4,
                        "windchill_c": 31.1,
                        "windchill_f": 88.0,
                        "heatindex_c": 35.2,
                        "heatindex_f": 95.4,
                        "dewpoint_c": 22.3,
                        "dewpoint_f": 72.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.7,
                        "gust_kph": 38.2,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692165600,
                        "time": "2023-08-16 15:00",
                        "temp_c": 30.9,
                        "temp_f": 87.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 20.4,
                        "wind_kph": 32.8,
                        "wind_degree": 179,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.67,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 61,
                        "cloud": 28,
                        "feelslike_c": 35.1,
                        "feelslike_f": 95.2,
                        "windchill_c": 30.9,
                        "windchill_f": 87.6,
                        "heatindex_c": 35.1,
                        "heatindex_f": 95.2,
                        "dewpoint_c": 22.6,
                        "dewpoint_f": 72.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.5,
                        "gust_kph": 37.8,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692169200,
                        "time": "2023-08-16 16:00",
                        "temp_c": 30.2,
                        "temp_f": 86.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 20.6,
                        "wind_kph": 33.1,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 65,
                        "cloud": 26,
                        "feelslike_c": 34.4,
                        "feelslike_f": 93.9,
                        "windchill_c": 30.2,
                        "windchill_f": 86.4,
                        "heatindex_c": 34.4,
                        "heatindex_f": 93.9,
                        "dewpoint_c": 22.8,
                        "dewpoint_f": 73.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.7,
                        "gust_kph": 38.2,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1692172800,
                        "time": "2023-08-16 17:00",
                        "temp_c": 29.6,
                        "temp_f": 85.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 20.1,
                        "wind_kph": 32.4,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 68,
                        "cloud": 31,
                        "feelslike_c": 33.6,
                        "feelslike_f": 92.5,
                        "windchill_c": 29.6,
                        "windchill_f": 85.3,
                        "heatindex_c": 33.6,
                        "heatindex_f": 92.5,
                        "dewpoint_c": 22.9,
                        "dewpoint_f": 73.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.5,
                        "gust_kph": 37.8,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692176400,
                        "time": "2023-08-16 18:00",
                        "temp_c": 28.8,
                        "temp_f": 83.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 19.7,
                        "wind_kph": 31.7,
                        "wind_degree": 178,
                        "wind_dir": "S",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 72,
                        "cloud": 16,
                        "feelslike_c": 32.7,
                        "feelslike_f": 90.9,
                        "windchill_c": 28.8,
                        "windchill_f": 83.8,
                        "heatindex_c": 32.7,
                        "heatindex_f": 90.9,
                        "dewpoint_c": 23.2,
                        "dewpoint_f": 73.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.2,
                        "gust_kph": 38.9,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1692180000,
                        "time": "2023-08-16 19:00",
                        "temp_c": 28.4,
                        "temp_f": 83.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 19.0,
                        "wind_kph": 30.6,
                        "wind_degree": 176,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 75,
                        "cloud": 22,
                        "feelslike_c": 32.3,
                        "feelslike_f": 90.1,
                        "windchill_c": 28.4,
                        "windchill_f": 83.1,
                        "heatindex_c": 32.3,
                        "heatindex_f": 90.1,
                        "dewpoint_c": 23.5,
                        "dewpoint_f": 74.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.2,
                        "gust_kph": 38.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692183600,
                        "time": "2023-08-16 20:00",
                        "temp_c": 28.1,
                        "temp_f": 82.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 18.6,
                        "wind_kph": 29.9,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 31,
                        "feelslike_c": 32.1,
                        "feelslike_f": 89.8,
                        "windchill_c": 28.1,
                        "windchill_f": 82.6,
                        "heatindex_c": 32.1,
                        "heatindex_f": 89.8,
                        "dewpoint_c": 23.7,
                        "dewpoint_f": 74.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 24.2,
                        "gust_kph": 38.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692187200,
                        "time": "2023-08-16 21:00",
                        "temp_c": 28.0,
                        "temp_f": 82.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 179,
                        "wind_dir": "S",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.73,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 78,
                        "cloud": 32,
                        "feelslike_c": 32.0,
                        "feelslike_f": 89.6,
                        "windchill_c": 28.0,
                        "windchill_f": 82.4,
                        "heatindex_c": 32.0,
                        "heatindex_f": 89.6,
                        "dewpoint_c": 23.9,
                        "dewpoint_f": 75.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 23.5,
                        "gust_kph": 37.8,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692190800,
                        "time": "2023-08-16 22:00",
                        "temp_c": 27.8,
                        "temp_f": 82.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 17.2,
                        "wind_kph": 27.7,
                        "wind_degree": 180,
                        "wind_dir": "S",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 27,
                        "feelslike_c": 31.8,
                        "feelslike_f": 89.2,
                        "windchill_c": 27.8,
                        "windchill_f": 82.0,
                        "heatindex_c": 31.8,
                        "heatindex_f": 89.2,
                        "dewpoint_c": 23.9,
                        "dewpoint_f": 75.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 22.6,
                        "gust_kph": 36.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1692194400,
                        "time": "2023-08-16 23:00",
                        "temp_c": 27.7,
                        "temp_f": 81.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 16.3,
                        "wind_kph": 26.3,
                        "wind_degree": 182,
                        "wind_dir": "S",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 23,
                        "feelslike_c": 31.6,
                        "feelslike_f": 88.9,
                        "windchill_c": 27.7,
                        "windchill_f": 81.9,
                        "heatindex_c": 31.6,
                        "heatindex_f": 88.9,
                        "dewpoint_c": 23.8,
                        "dewpoint_f": 74.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 21.5,
                        "gust_kph": 34.6,
                        "uv": 1.0
                    }
                ]
            }
        ]
    },
    "alerts": {
        "alert": [
            
        ]
    }
}